[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"
nixpacksVersion = "latest"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port=${PORT}"
healthcheckPath = "/"
healthcheckTimeout = 100 